### PR TITLE
Removal of compat layer (1/2)

### PR DESCRIPTION
**Pull request by tmathern**
## Description

Removes the compatibility layer we used to transition workers after sdk refactoring (it has been deprecated for some months, now). Time to remove it!

Fixes #NUI-483.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexkli** [comment]
Did we update all our workers already? I have never seen a confirmation that this was done.

**Comment by tmathern** [comment]
https://circle.ci.adobeitc.com/gh/nui/ci-opensource/5325 is doing just fine (dependent_module_tests).
A search on the function exported by `compat.js` in our workers also doesn't find hits.

**Comment by tmathern** [comment]
(I didn't update experimental-prototype workers, since when we would productize them we would re-work them/re-verify them anyway).

**Comment by alexkli** [comment]
Note that `27.1.0` was an erroneous release. It was unpublished.

**Pull request merged**
