### PR TITLE
Add support for input files of format JPEG 2000 

### PR DESCRIPTION
**Pull request by tmathern**
## Description

- Adds support for files whose input format is has [JPEG 2000](https://en.wikipedia.org/wiki/JPEG_2000) extension (.jp2, .j2k, .jpf, .jpg2, .j2c, .jpc or .jpx).
- Adds tests for the newly supported extensions.
- Note that some of those extensions already were supported because exiftool identifies them as JPEG. Other extensions, like `jp2` and `j2c`, were not identified as JPEG but as `JP2` and `J2C` respectively. The PR updates the postprocessing logic to extend supported input files with J2C and JP2.

- Adds JPEG2000 support mostly because I noticed other tools (eg. Acrobat) have JPEG2000 support too.

Fixes #N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jdelbick** [comment]
QS: does core pass through the source file types already or will this require a change?

**Comment by tmathern** [comment]
@jdelbick No change needed in core.

**Comment by jdelbick** [comment]
fyi the reason I have not submitted a review for this PR yet is that I am wondering:
1. Do we claim to support these formats already? (if so, yes let's merge this PR)
2. If not, do we want to support these formats?
cc/ @chandarn

**Comment by tmathern** [comment]
@jdelbick `Do we claim to support these formats already? (if so, yes let's merge this PR)`
Yes and no. We support some JPEG2000... which have (often wrongfully)the `jpeg` extension.
The JPEG2000 family spans over some `jpeg` extensions (we have some test with jpeg extensions which are actually jpeg2000) and some more extensions. This just adds the missing extensions support.

**Comment by tmathern** [comment]
This PR has been open for some time now. I'll close it, and reopen if there is more demand.

**Pull request closed without merging**
