### PR TITLE
update dependency

### PR DESCRIPTION
**Pull request by pheenomenon**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tmathern** [comment]
@pheenomenon Please consider rather merging into that branch: https://github.com/adobe/asset-compute-sdk/pull/106, as it contains fixes for failing unit tests. Thanks!

**Comment by tmathern** [comment]
@pheenomenon The ajv update seems to have breaking changes that affect us. It breaks existing unit tests. To make sure the newest version gets picked up: removes the `packages-lock` file and reinstall dependencies (commit and push the new packages-lock file). Then **unit tests should fail when running on node:10.**

**Comment by tmathern** [comment]
You may also need to check tests results from `Adobe CI - dependent_module_tests` manually, as they may not be flagged correctly as failing without https://github.com/adobe/asset-compute-sdk/pull/106...

**Comment by pheenomenon** [comment]
Closing this in lieu of https://github.com/adobe/asset-compute-sdk/pull/111

**Pull request closed without merging**
